# Generated by Django 6.0.5 on 2026-05-29 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('unit', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'work_types',
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('volume', models.DecimalField(decimal_places=2, max_digits=12)),
                ('executor', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='journal.worktype')),
            ],
            options={
                'db_table': 'work_logs',
                'ordering': ['-work_date'],
            },
        ),
    ]
